# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

markdown:         kramdown
highlighter:      rouge


title: The Grey Corner
tagline: "Stuff"
description: >- # this means to ignore newlines until "baseurl:"
  Stephen Bradshaw's blog about pentesting and computer security  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SM_Bradshaw
github_username:  stephenbradshaw
author: 
  name: Stephen Bradshaw
  #url: github.com/stephenbradshaw


# configure these to enable disqus
#disqus:
  #shortname: my-disqus-shortname


# Build settings
# theme: minima
# theme: jekyll-theme-hacker
# theme: jekyll-theme-minimal
# theme: jekyll-theme-dinky

# https://github.com/fongandrew/hydeout
remote_theme: erikh/hydeout
#remote_theme: dbtek/dbyll


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: UA-180079318-1
logo: assets/img/logo.png

markdown:         redcarpet
highlighter:      pygments

paginate:         2

# Custom vars
# version:          0.1 pre pre pre alpha

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
